author: "Tobe O <thosakwe@gmail.com>"
description: "Angel hook to compress resonses in a variety of formats."
homepage: "https://github.com/angel-dart/compress.git"
name: "angel_compress"
version: "1.0.0-dev"
dependencies: 
  angel_framework: "^1.0.0-dev.34"
dev_dependencies:
  crypto: "^2.0.1"
  test: "^0.12.18"
