author: "Tobe O <thosakwe@gmail.com>"
description: "Angel hook to compress resonses in a variety of formats."
environment:
  sdk: ">=1.19.0"
homepage: "https://github.com/angel-dart/compress.git"
name: "angel_compress"
version: "1.0.0"
dependencies: 
  angel_framework: "^1.0.0-dev.34"
dev_dependencies:
  lzw: "^0.1.0"
  test: "^0.12.18"
